apiVersion: v1
kind: Pod
metadata:
  name: utils-2
spec:
  containers:
    - name: utils
      image: utils:0.01
      command: ["bash", "-c", 'while true; do echo "hi!"; done']
  nodeSelector:
    node: "2"
