apiVersion: v1
kind: Pod
metadata:
  name: utils-0
spec:
  containers:
    - name: utils
      image: utils:0.01
      command: ["bash", "-c", 'while true; do echo "hi!"; done']
  nodeSelector:
    node: "0"
