apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
      - name: conf-dir
        configMap:
          name: kafka-config
#      securityContext:
#        runAsUser: 1000
#        fsGroup: 1000
      containers:
      - name: kubernetes-kafka
        imagePullPolicy: IfNotPresent
        image: "fwt/kafka"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 9092
          name: server
        command:
        - sh
        - -c
        - "start-kafka"
#        readinessProbe:
#          exec:
#            command:
#            - sh
#            - -c
#            - "zookeeper-ready 2181"
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
#        livenessProbe:
#          exec:
#            command:
#            - sh
#            - -c
#            - "zookeeper-ready 2181"
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
        volumeMounts:
        - name: conf-dir
          mountPath: /opt/kafka/config
        - name: data-dir
          mountPath: /data/kafka
  volumeClaimTemplates:
  - metadata:
      name: data-dir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
