#!/usr/bin/env bash
docker build . -f Dockerfile.alpine -t fwt/kafka
docker save fwt/kafka -o kafka.tar

ANSIBLE=$(which ansible)

if [ $ANSIBLE ]
then
    $ANSIBLE vms -f 3 -m copy -a "src=kafka.tar dest=/root/kafka.tar"
else
    for i in 1 2 3; do
        scp kafka.tar root@k8s-node$i:/root
    done
fi
