apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kafka-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.72
    path: /nfsroot/kafka/kafka-2
